FROM node:12.13.0-alpine

ENV PORT 3000

WORKDIR /app


# Add package.json to install dependencies
ADD ./package.json /app/package.json
RUN npm config set registry http://registry.npmjs.org
RUN npm install

#Copy sources
ADD ./src /app/src

# Build the sources
RUN npm run build

# remove unnecessary files
RUN rm -rf ./src

# Expose the port
EXPOSE $PORT

CMD ["node", "main"]